blank_issues_enabled: false
contact_links:
  - name: Joyebdiy related issues
    url: https://github.com/joyebdev/joyeb-diy/issues/new/choose
    about: Report issues related to Joyebdiy.
  - name: Chat
    url: https://thinktank.ottomator.ai
    about: Ask questions and discuss with other Joyebdiy users.
